$_J("org.eclipse.swt.internal.xhtml");
c$=$_C(function(){
this.contentWindow=null;
this.parentNode=null;
this.childNodes=null;
this.nextSibling=null;
this.offsetLeft=0;
this.offsetTop=0;
this.offsetParent=null;
this.style=null;
this.id=null;
this.innerHTML=null;
this.innerText=null;
this.value=null;
this.type=null;
this.href=null;
this.target=null;
this.title=null;
this.onclick=null;
this.onkeypress=null;
this.onkeydown=null;
this.onkeyup=null;
this.oncontextmenu=null;
this.size=0;
this.selectedIndex=0;
this.options=null;
this.nodeName=null;
this.className=null;
this.onmousedown=null;
this.onmouseup=null;
this.ondblclick=null;
this.onselectstart=null;
this.checked=false;
this.readOnly=false;
this.onchange=null;
this.onselectchange=null;
this.width=0;
this.height=0;
this.offsetWidth=0;
this.clientWidth=0;
this.scrollWidth=0;
this.offsetHeight=0;
this.clientHeight=0;
this.scrollHeight=0;
this.src=null;
this.alt=null;
this.disabled=false;
this.onLoseCapture=null;
this.onfocusout=null;
this.onmousemove=null;
this.onmouseover=null;
this.onmouseout=null;
this.onfocus=null;
this.onblur=null;
this.onhelp=null;
$_Z(this,arguments);
},$wt.internal.xhtml,"Element");
$_M(c$,"appendChild",
function(child){
},"$wt.internal.xhtml.Element");
$_M(c$,"select",
function(){
});
$_M(c$,"focus",
function(){
});
$_M(c$,"removeChild",
function(handle){
},"$wt.internal.xhtml.Element");
$_M(c$,"add",
function(object){
},"~O");
$_M(c$,"insertBefore",
function(newTR,tbodyTR){
},"$wt.internal.xhtml.Element,$wt.internal.xhtml.Element");
$_M(c$,"getElementsByTagName",
function(tag){
return new Array(0);
},"~S");
$_M(c$,"cloneNode",
function(flag){
return new Element();
},"~B");
