$_J("org.eclipse.swt.internal.xhtml");
c$=$_C(function(){
$_Z(this,arguments);
},$wt.internal.xhtml,"History");
$_M(c$,"forward",
function(){
});
$_M(c$,"back",
function(){
});
$_M(c$,"go",
function(location){
},"~S");
