$_J("org.eclipse.swt.printing");
$_L(["$wt.graphics.DeviceData"],"$wt.printing.PrinterData",null,function(){
c$=$_C(function(){
this.driver=null;
this.name=null;
this.scope=0;
this.startPage=0;
this.endPage=0;
this.printToFile=false;
this.fileName=null;
this.copyCount=1;
this.collate=false;
this.otherData=null;
$_Z(this,arguments);
},$wt.printing,"PrinterData",$wt.graphics.DeviceData);
$_K(c$,
function(){
$_R(this,$wt.printing.PrinterData,[]);
});
$_K(c$,
function(driver,name){
$_R(this,$wt.printing.PrinterData,[]);
this.driver=driver;
this.name=name;
},"~S,~S");
$_V(c$,"toString",
function(){
return"PrinterData {driver = "+this.driver+", name = "+this.name+"}";
});
$_S(c$,
"ALL_PAGES",0,
"PAGE_RANGE",1,
"SELECTION",2);
});
