$_J("net.sf.j2s.ajax");
Clazz.load(["net.sf.j2s.ajax.IXHRCallback"],"net.sf.j2s.ajax.XHRCallbackAdapter",null,function(){
c$=$_C(function(){
$_Z(this,arguments);
},net.sf.j2s.ajax,"XHRCallbackAdapter",null,net.sf.j2s.ajax.IXHRCallback);
$_V(c$,"onComplete",
function(){
});
$_V(c$,"onInteractive",
function(){
});
$_V(c$,"onLoaded",
function(){
});
$_V(c$,"onLoading",
function(){
});
});
