$_J("net.sf.j2s.ajax");
$_L(["net.sf.j2s.ajax.IXHRCallback"],"net.sf.j2s.ajax.XHRCallbackSWTAdapter",null,function(){
c$=$_T(net.sf.j2s.ajax,"XHRCallbackSWTAdapter",null,net.sf.j2s.ajax.IXHRCallback);
$_M(c$,"swtOnComplete",
function(){
});
$_M(c$,"swtOnInteractive",
function(){
});
$_M(c$,"swtOnLoaded",
function(){
});
$_M(c$,"swtOnLoading",
function(){
});
$_V(c$,"onComplete",
function(){
this.swtOnComplete();
});
$_V(c$,"onInteractive",
function(){
this.swtOnInteractive();
});
$_V(c$,"onLoaded",
function(){
this.swtOnLoaded();
});
$_V(c$,"onLoading",
function(){
this.swtOnLoading();
});
});
