c$=$_C(function(){
this.returnSet=0;
this.returnBoolean=false;
this.returnNumber=0;
this.returnObject=null;
this.event=null;
$_Z(this,arguments);
},$wt.internal,"RunnableCompatibility",null,Runnable);
$_M(c$,"getEvent",
function(){
return this.event;
});
$_M(c$,"setEvent",
function(event){
this.event=event;
},"~O");
$_M(c$,"toReturn",
function(val){
this.returnSet=1;
this.returnNumber=val;
this.returnObject=null;
},"~N");
$_M(c$,"toReturn",
function(val){
this.returnSet=2;
this.returnBoolean=val;
this.returnNumber=0;
this.returnObject=null;
},"~B");
$_M(c$,"toReturn",
function(val){
this.returnSet=3;
this.returnObject=val;
this.returnNumber=0;
this.returnBoolean=false;
},"~O");
$_M(c$,"isReturned",
function(){
return this.returnSet!=0;
});
