$_L(["$wt.events.ControlListener"],"$wt.events.ControlAdapter",null,function(){
c$=$_T($wt.events,"ControlAdapter",null,$wt.events.ControlListener);
$_V(c$,"controlMoved",
function(e){
},"$wt.events.ControlEvent");
$_V(c$,"controlResized",
function(e){
},"$wt.events.ControlEvent");
});
