$_L(["$wt.events.KeyListener"],"$wt.events.KeyAdapter",null,function(){
c$=$_T($wt.events,"KeyAdapter",null,$wt.events.KeyListener);
$_V(c$,"keyPressed",
function(e){
},"$wt.events.KeyEvent");
$_V(c$,"keyReleased",
function(e){
},"$wt.events.KeyEvent");
});
