$_L(["$wt.custom.CTabFolder2Listener"],"$wt.custom.CTabFolder2Adapter",null,function(){
c$=$_T($wt.custom,"CTabFolder2Adapter",null,$wt.custom.CTabFolder2Listener);
$_V(c$,"close",
function(event){
},"$wt.custom.CTabFolderEvent");
$_V(c$,"minimize",
function(event){
},"$wt.custom.CTabFolderEvent");
$_V(c$,"maximize",
function(event){
},"$wt.custom.CTabFolderEvent");
$_V(c$,"restore",
function(event){
},"$wt.custom.CTabFolderEvent");
$_V(c$,"showList",
function(event){
},"$wt.custom.CTabFolderEvent");
});
