$_L(["$wt.events.TypedEvent"],"$wt.custom.LineStyleEvent",null,function(){
c$=$_C(function(){
this.lineOffset=0;
this.lineText=null;
this.styles=null;
$_Z(this,arguments);
},$wt.custom,"LineStyleEvent",$wt.events.TypedEvent);
$_K(c$,
function(e){
$_R(this,$wt.custom.LineStyleEvent,[e]);
this.lineOffset=e.detail;
this.lineText=e.text;
this.styles=e.styles;
},"$wt.custom.StyledTextEvent");
});
