Clazz.load(["$wt.events.TypedEvent"],"$wt.browser.LocationEvent",null,function(){
c$=$_C(function(){
this.location=null;
this.top=false;
this.doit=false;
$_Z(this,arguments);
},$wt.browser,"LocationEvent",$wt.events.TypedEvent);
$_K(c$,
function(w){
$_R(this,$wt.browser.LocationEvent,[w]);
},"$wt.widgets.Widget");
$_S(c$,
"serialVersionUID",3906644198244299574);
});
