$_L(["$wt.browser.LocationListener"],"$wt.browser.LocationAdapter",null,function(){
c$=$_T($wt.browser,"LocationAdapter",null,$wt.browser.LocationListener);
$_V(c$,"changing",
function(event){
},"$wt.browser.LocationEvent");
$_V(c$,"changed",
function(event){
},"$wt.browser.LocationEvent");
});
