$_L(["$wt.browser.VisibilityWindowListener"],"$wt.browser.VisibilityWindowAdapter",null,function(){
c$=$_T($wt.browser,"VisibilityWindowAdapter",null,$wt.browser.VisibilityWindowListener);
$_V(c$,"hide",
function(event){
},"$wt.browser.WindowEvent");
$_V(c$,"show",
function(event){
},"$wt.browser.WindowEvent");
});
