$_J("org.eclipse.swt.internal.xhtml");
c$=$_C(function(){
this.document=null;
this.location=null;
this.history=null;
$_Z(this,arguments);
},$wt.internal.xhtml,"ContentWindow");
$_M(c$,"reload",
function(){
});
$_M(c$,"stop",
function(){
});
