$_L(["$wt.accessibility.AccessibleListener"],"$wt.accessibility.AccessibleAdapter",null,function(){
c$=$_T($wt.accessibility,"AccessibleAdapter",null,$wt.accessibility.AccessibleListener);
$_V(c$,"getName",
function(e){
},"$wt.accessibility.AccessibleEvent");
$_V(c$,"getHelp",
function(e){
},"$wt.accessibility.AccessibleEvent");
$_V(c$,"getKeyboardShortcut",
function(e){
},"$wt.accessibility.AccessibleEvent");
$_V(c$,"getDescription",
function(e){
},"$wt.accessibility.AccessibleEvent");
});
