Clazz.load(["$wt.widgets.Item"],"$wt.widgets.TrayItem",["$wt.widgets.TypedListener"],function(){
c$=$_C(function(){
this.parent=null;
this.id=0;
this.image2=null;
this.toolTipText=null;
this.visible=true;
$_Z(this,arguments);
},$wt.widgets,"TrayItem",$wt.widgets.Item);
$_K(c$,
function(parent,style){
$_R(this,$wt.widgets.TrayItem,[parent,style]);
this.parent=parent;
parent.createItem(this,parent.getItemCount());
this.createWidget();
},"$wt.widgets.Tray,~N");
$_M(c$,"addSelectionListener",
function(listener){
var typedListener=new $wt.widgets.TypedListener(listener);
this.addListener(13,typedListener);
this.addListener(14,typedListener);
},"$wt.events.SelectionListener");
$_M(c$,"createWidget",
function(){
});
$_M(c$,"getToolTipText",
function(){
return this.toolTipText;
});
$_M(c$,"getVisible",
function(){
return this.visible;
});
$_M(c$,"recreate",
function(){
this.createWidget();
if(!this.visible)this.setVisible(false);
if(this.text.length!=0)this.setText(this.text);
if(this.image!=null)this.setImage(this.image);
if(this.toolTipText!=null)this.setToolTipText(this.toolTipText);
});
$_M(c$,"releaseChild",
function(){
$_U(this,$wt.widgets.TrayItem,"releaseChild",[]);
this.parent.destroyItem(this);
});
$_M(c$,"releaseWidget",
function(){
$_U(this,$wt.widgets.TrayItem,"releaseWidget",[]);
if(this.image2!=null)this.image2.dispose();
this.image2=null;
this.toolTipText=null;
});
$_M(c$,"removeSelectionListener",
function(listener){
if(this.eventTable==null)return;
this.eventTable.unhook(13,listener);
this.eventTable.unhook(14,listener);
},"$wt.events.SelectionListener");
$_M(c$,"setImage",
function(image){
$_U(this,$wt.widgets.TrayItem,"setImage",[image]);
if(this.image2!=null)this.image2.dispose();
this.image2=null;
},"$wt.graphics.Image");
$_M(c$,"setToolTipText",
function(value){
this.toolTipText=value;
},"~S");
$_M(c$,"setVisible",
function(visible){
if(this.visible==visible)return;
if(visible){
this.sendEvent(22);
if(this.isDisposed())return;
}this.visible=visible;
if(!visible)this.sendEvent(23);
},"~B");
});
