$_L(["$wt.accessibility.AccessibleControlListener"],"$wt.accessibility.AccessibleControlAdapter",null,function(){
c$=$_T($wt.accessibility,"AccessibleControlAdapter",null,$wt.accessibility.AccessibleControlListener);
$_V(c$,"getChildAtPoint",
function(e){
},"$wt.accessibility.AccessibleControlEvent");
$_V(c$,"getLocation",
function(e){
},"$wt.accessibility.AccessibleControlEvent");
$_V(c$,"getChild",
function(e){
},"$wt.accessibility.AccessibleControlEvent");
$_V(c$,"getChildCount",
function(e){
},"$wt.accessibility.AccessibleControlEvent");
$_V(c$,"getDefaultAction",
function(e){
},"$wt.accessibility.AccessibleControlEvent");
$_V(c$,"getFocus",
function(e){
},"$wt.accessibility.AccessibleControlEvent");
$_V(c$,"getRole",
function(e){
},"$wt.accessibility.AccessibleControlEvent");
$_V(c$,"getSelection",
function(e){
},"$wt.accessibility.AccessibleControlEvent");
$_V(c$,"getState",
function(e){
},"$wt.accessibility.AccessibleControlEvent");
$_V(c$,"getValue",
function(e){
},"$wt.accessibility.AccessibleControlEvent");
$_V(c$,"getChildren",
function(e){
},"$wt.accessibility.AccessibleControlEvent");
});
