$_L(["$wt.dnd.DragSourceListener"],"$wt.dnd.DragSourceAdapter",null,function(){
c$=$_T($wt.dnd,"DragSourceAdapter",null,$wt.dnd.DragSourceListener);
$_V(c$,"dragStart",
function(event){
},"$wt.dnd.DragSourceEvent");
$_V(c$,"dragFinished",
function(event){
},"$wt.dnd.DragSourceEvent");
$_V(c$,"dragSetData",
function(event){
},"$wt.dnd.DragSourceEvent");
});
