$_L(["$wt.events.TypedEvent"],"$wt.dnd.DragSourceEvent",null,function(){
c$=$_C(function(){
this.detail=0;
this.doit=false;
this.dataType=null;
$_Z(this,arguments);
},$wt.dnd,"DragSourceEvent",$wt.events.TypedEvent);
$_K(c$,
function(e){
$_R(this,$wt.dnd.DragSourceEvent,[e]);
this.data=e.data;
this.detail=e.detail;
this.doit=e.doit;
this.dataType=e.dataType;
},"$wt.dnd.DNDEvent");
$_M(c$,"updateEvent",
function(e){
e.widget=this.widget;
e.time=this.time;
e.data=this.data;
e.detail=this.detail;
e.doit=this.doit;
e.dataType=this.dataType;
},"$wt.dnd.DNDEvent");
});
