$_L(["$wt.events.TypedEvent"],"$wt.dnd.DropTargetEvent",null,function(){
c$=$_C(function(){
this.x=0;
this.y=0;
this.detail=0;
this.operations=0;
this.feedback=0;
this.item=null;
this.currentDataType=null;
this.dataTypes=null;
$_Z(this,arguments);
},$wt.dnd,"DropTargetEvent",$wt.events.TypedEvent);
$_K(c$,
function(e){
$_R(this,$wt.dnd.DropTargetEvent,[e]);
this.data=e.data;
this.x=e.x;
this.y=e.y;
this.detail=e.detail;
this.currentDataType=e.dataType;
this.dataTypes=e.dataTypes;
this.operations=e.operations;
this.feedback=e.feedback;
this.item=e.item;
},"$wt.dnd.DNDEvent");
$_M(c$,"updateEvent",
function(e){
e.widget=this.widget;
e.time=this.time;
e.data=this.data;
e.x=this.x;
e.y=this.y;
e.detail=this.detail;
e.dataType=this.currentDataType;
e.dataTypes=this.dataTypes;
e.operations=this.operations;
e.feedback=this.feedback;
e.item=this.item;
},"$wt.dnd.DNDEvent");
});
