$_L(["$wt.dnd.DragUnderEffect"],"$wt.dnd.NoDragUnderEffect",null,function(){
c$=$_T($wt.dnd,"NoDragUnderEffect",$wt.dnd.DragUnderEffect);
$_K(c$,
function(control){
$_R(this,$wt.dnd.NoDragUnderEffect,[]);
},"$wt.widgets.Control");
$_V(c$,"show",
function(effect,x,y){
},"~N,~N,~N");
});
