Clazz.load(["$wt.events.TypedEvent"],"$wt.events.DisposeEvent",null,function(){
c$=$_C(function(){
$_Z(this,arguments);
},$wt.events,"DisposeEvent",$wt.events.TypedEvent);
$_K(c$,
function(e){
$_R(this,$wt.events.DisposeEvent,[e]);
},"$wt.widgets.Event");
$_S(c$,
"serialVersionUID",3257566187633521206);
});
