Clazz.load(["$wt.events.MouseListener"],"$wt.events.MouseAdapter",null,function(){
c$=$_C(function(){
$_Z(this,arguments);
},$wt.events,"MouseAdapter",null,$wt.events.MouseListener);
$_V(c$,"mouseDoubleClick",
function(e){
},"$wt.events.MouseEvent");
$_V(c$,"mouseDown",
function(e){
},"$wt.events.MouseEvent");
$_V(c$,"mouseUp",
function(e){
},"$wt.events.MouseEvent");
});
