Clazz.load(["$wt.events.ShellListener"],"$wt.events.ShellAdapter",null,function(){
c$=$_C(function(){
$_Z(this,arguments);
},$wt.events,"ShellAdapter",null,$wt.events.ShellListener);
$_V(c$,"shellActivated",
function(e){
},"$wt.events.ShellEvent");
$_V(c$,"shellClosed",
function(e){
},"$wt.events.ShellEvent");
$_V(c$,"shellDeactivated",
function(e){
},"$wt.events.ShellEvent");
$_V(c$,"shellDeiconified",
function(e){
},"$wt.events.ShellEvent");
$_V(c$,"shellIconified",
function(e){
},"$wt.events.ShellEvent");
});
