Clazz.load(["$wt.events.TypedEvent"],"$wt.browser.ProgressEvent",null,function(){
c$=$_C(function(){
this.current=0;
this.total=0;
$_Z(this,arguments);
},$wt.browser,"ProgressEvent",$wt.events.TypedEvent);
$_K(c$,
function(w){
$_R(this,$wt.browser.ProgressEvent,[w]);
},"$wt.widgets.Widget");
$_S(c$,
"serialVersionUID",3977018427045393972);
});
