$_L(["$wt.dnd.DropTargetListener"],"$wt.dnd.DropTargetAdapter",null,function(){
c$=$_T($wt.dnd,"DropTargetAdapter",null,$wt.dnd.DropTargetListener);
$_V(c$,"dragEnter",
function(event){
},"$wt.dnd.DropTargetEvent");
$_V(c$,"dragLeave",
function(event){
},"$wt.dnd.DropTargetEvent");
$_V(c$,"dragOperationChanged",
function(event){
},"$wt.dnd.DropTargetEvent");
$_V(c$,"dragOver",
function(event){
},"$wt.dnd.DropTargetEvent");
$_V(c$,"drop",
function(event){
},"$wt.dnd.DropTargetEvent");
$_V(c$,"dropAccept",
function(event){
},"$wt.dnd.DropTargetEvent");
});
