$_L(["$wt.events.MenuListener"],"$wt.events.MenuAdapter",null,function(){
c$=$_T($wt.events,"MenuAdapter",null,$wt.events.MenuListener);
$_V(c$,"menuHidden",
function(e){
},"$wt.events.MenuEvent");
$_V(c$,"menuShown",
function(e){
},"$wt.events.MenuEvent");
});
