$_L(["$wt.events.SelectionListener"],"$wt.events.SelectionAdapter",null,function(){
c$=$_T($wt.events,"SelectionAdapter",null,$wt.events.SelectionListener);
$_V(c$,"widgetSelected",
function(e){
},"$wt.events.SelectionEvent");
$_V(c$,"widgetDefaultSelected",
function(e){
},"$wt.events.SelectionEvent");
});
