//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.20 at 11:47:26 AM GMT 
//


package test.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FilterBy.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FilterBy">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="byLabel"/>
 *     &lt;enumeration value="byScore"/>
 *     &lt;enumeration value="byAttribute"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FilterBy", namespace = "www.jalview.org/colours")
@XmlEnum
public enum FilterBy {

    @XmlEnumValue("byLabel")
    BY_LABEL("byLabel"),
    @XmlEnumValue("byScore")
    BY_SCORE("byScore"),
    @XmlEnumValue("byAttribute")
    BY_ATTRIBUTE("byAttribute");
    private final String value;

    FilterBy(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FilterBy fromValue(String v) {
        for (FilterBy c: FilterBy.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
