c$=$_C(function(){
this.display=null;
this.messageCount=0;
this.messageLock=null;
this.syncThread=null;
$_Z(this,arguments);
},$wt.widgets,"Synchronizer");
$_Y(c$,function(){
this.messageLock=new JavaObject();
});
$_K(c$,
function(display){
this.display=display;
},"$wt.widgets.Display");
$_M(c$,"asyncExec",
function(runnable){
if(runnable==null){
this.display.wake();
return;
}},"Runnable");
$_M(c$,"getMessageCount",
function(){
{
return this.messageCount;
}});
$_M(c$,"releaseSynchronizer",
function(){
this.display=null;
this.messageLock=null;
this.syncThread=null;
});
$_M(c$,"syncExec",
function(runnable){
if(this.display.isValidThread()){
if(runnable!=null)runnable.run();
return;
}if(runnable==null){
this.display.wake();
return;
}},"Runnable");
