$_L(["$wt.widgets.Event"],"$wt.custom.StyledTextEvent",null,function(){
c$=$_C(function(){
this.styles=null;
this.lineBackground=null;
this.segments=null;
this.replaceCharCount=0;
this.newCharCount=0;
this.replaceLineCount=0;
this.newLineCount=0;
$_Z(this,arguments);
},$wt.custom,"StyledTextEvent",$wt.widgets.Event);
$_K(c$,
function(content){
$_R(this,$wt.custom.StyledTextEvent);
this.data=content;
},"$wt.custom.StyledTextContent");
});
