$_J("net.sf.j2s.ajax");
Clazz.load(["net.sf.j2s.ajax.IXHRCallback"],null,function(){
c$=$_C(function(){
$_Z(this,arguments);
},net.sf.j2s.ajax,"XHRCallbackSWTAdapter",null,net.sf.j2s.ajax.IXHRCallback);
$_M(c$,"swtOnComplete",
function(){
});
$_M(c$,"swtOnInteractive",
function(){
});
$_M(c$,"swtOnLoaded",
function(){
});
$_M(c$,"swtOnLoading",
function(){
});
$_V(c$,"onComplete",
function(){
this.swtOnComplete();
});
$_V(c$,"onInteractive",
function(){
this.swtOnInteractive();
});
$_V(c$,"onLoaded",
function(){
this.swtOnLoaded();
});
$_V(c$,"onLoading",
function(){
this.swtOnLoading();
});
});
