$_J("net.sf.j2s.ajax");
$_L(["net.sf.j2s.ajax.IXHRCallback"],"net.sf.j2s.ajax.XHRCallbackAdapter",null,function(){
c$=$_T(net.sf.j2s.ajax,"XHRCallbackAdapter",null,net.sf.j2s.ajax.IXHRCallback);
$_V(c$,"onComplete",
function(){
});
$_V(c$,"onInteractive",
function(){
});
$_V(c$,"onLoaded",
function(){
});
$_V(c$,"onLoading",
function(){
});
});
